create table if not exists public.enquiries (
  id uuid primary key default gen_random_uuid(),
  type text,
  first_name text,
  last_name text,
  name text,
  email text,
  phone text,
  interest text,
  budget text,
  area text,
  property_id text,
  property_title text,
  message text,
  source text default 'website',
  status text default 'new',
  assigned_to text,
  action_log jsonb default '[]'::jsonb,
  chat_profile jsonb default '{}'::jsonb,
  chat_transcript text,
  tracking jsonb default '{}'::jsonb,
  newsletter_subscribed boolean default false,
  newsletter_subscribed_at timestamptz,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.enquiries
add column if not exists area text,
add column if not exists property_id text,
add column if not exists property_title text,
add column if not exists assigned_to text,
add column if not exists action_log jsonb default '[]'::jsonb,
add column if not exists chat_profile jsonb default '{}'::jsonb,
add column if not exists chat_transcript text,
add column if not exists tracking jsonb default '{}'::jsonb,
add column if not exists newsletter_subscribed boolean default false,
add column if not exists newsletter_subscribed_at timestamptz,
add column if not exists payload jsonb default '{}'::jsonb;

create table if not exists public.crm_leads (
  id uuid primary key default gen_random_uuid(),
  source_submission_id uuid,
  name text not null,
  first_name text,
  last_name text,
  email text not null,
  phone text,
  alternate_phone text,
  whatsapp_number text,
  preferred_channel text,
  preferred_language text,
  preferred_contact_time text,
  nationality text,
  country text,
  city text,
  residence_status text,
  client_type text,
  property_type_interest jsonb default '[]'::jsonb,
  preferred_locations jsonb default '[]'::jsonb,
  bedrooms_preference jsonb default '[]'::jsonb,
  budget_min numeric default 0,
  budget_max numeric default 0,
  financing_method text,
  mortgage_pre_approval boolean default false,
  purchase_timeframe text,
  lead_source text default 'website',
  source_campaign text,
  lead_score integer default 0,
  temperature text,
  status text default 'New',
  assigned_to text,
  last_activity_date timestamptz,
  next_follow_up_date date,
  notes text,
  description text,
  action_log jsonb default '[]'::jsonb,
  property_interests jsonb default '[]'::jsonb,
  opportunities jsonb default '[]'::jsonb,
  tasks jsonb default '[]'::jsonb,
  deals jsonb default '[]'::jsonb,
  communications jsonb default '[]'::jsonb,
  attachments jsonb default '[]'::jsonb,
  viewings jsonb default '[]'::jsonb,
  offers jsonb default '[]'::jsonb,
  status_history jsonb default '[]'::jsonb,
  chat_profile jsonb default '{}'::jsonb,
  chat_transcript text,
  tracking jsonb default '{}'::jsonb,
  validation_call_consent boolean default false,
  validation_call_consent_at timestamptz,
  availability_requested boolean default false,
  project_interest text,
  newsletter_subscribed boolean default false,
  newsletter_subscribed_at timestamptz,
  lost_reason text,
  win_details jsonb default '{}'::jsonb,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.crm_leads
add column if not exists alternate_phone text,
add column if not exists whatsapp_number text,
add column if not exists deals jsonb default '[]'::jsonb,
add column if not exists communications jsonb default '[]'::jsonb,
add column if not exists attachments jsonb default '[]'::jsonb,
add column if not exists viewings jsonb default '[]'::jsonb,
add column if not exists offers jsonb default '[]'::jsonb,
add column if not exists status_history jsonb default '[]'::jsonb,
add column if not exists chat_profile jsonb default '{}'::jsonb,
add column if not exists chat_transcript text,
add column if not exists tracking jsonb default '{}'::jsonb,
add column if not exists validation_call_consent boolean default false,
add column if not exists validation_call_consent_at timestamptz,
add column if not exists availability_requested boolean default false,
add column if not exists project_interest text,
add column if not exists newsletter_subscribed boolean default false,
add column if not exists newsletter_subscribed_at timestamptz,
add column if not exists lost_reason text,
add column if not exists win_details jsonb default '{}'::jsonb,
add column if not exists payload jsonb default '{}'::jsonb;

create table if not exists public.crm_duplicate_leads (
  id uuid primary key default gen_random_uuid(),
  original_id text,
  source_type text,
  name text,
  email text,
  phone text,
  duplicate_reason text,
  admin_note text,
  payload jsonb not null default '{}'::jsonb,
  archived_at timestamptz default now(),
  archived_by text default 'admin'
);

create index if not exists idx_crm_leads_email on public.crm_leads (lower(email));
create index if not exists idx_crm_leads_phone on public.crm_leads (phone);
create index if not exists idx_crm_leads_status on public.crm_leads (status);
create index if not exists idx_crm_leads_score on public.crm_leads (lead_score);
create index if not exists idx_crm_enquiries_status on public.enquiries (status);
